#!/usr/bin/env -S cargo +nightly -Zscript
---cargo
[package]
edition = "2021"
---

fn main() {
    let title = std::env::args().nth(1).unwrap_or_else(|| "report".to_string());
    println!("=== {} ===", title);
    println!("Generated by a cargo-script (RFC 3502).");
}
